name: AutoYouthStudy

on: 
  workflow_dispatch:
  push:
  pull_request:
  watch:
    types: [ started ]
  schedule:
    - cron: 15 12 * * 1

jobs:
  newspush:
    runs-on: ubuntu-latest
    steps :
      - name: checkout
        uses: actions/checkout@v3

      - name: setup-python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10' 
      
      - name: Install dependencies
        run: |
          python3 -m pip install --upgrade pip
          pip install requests 
          pip install dingtalkchatbot 
      
      - name: send
        env:
          OPENID: ${{ secrets.OPENID }}
          DING_WEBHOOK: ${{ secrets.DING_WEBHOOK }}
          DING_SECRET: ${{ secrets.DING_SECRET }}
        run: python3 ZheJiangAuto.py